bobMinimumVersion: "1.2.0rc1"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/codelabs-ch/basement.git
    commit: df866d182cf7b3856a099f22a94b3fd38cad87a1
    branch: master-b79927c309a0+codelabs

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/codelabs-ch/basement-gnu-linux.git
    commit: 393f41a5f2563d21521fe3bb80681ea85e2123a8
    branch: master-c1d98bf23f1f+codelabs

  - name: ada
    scm: git
    url: https://git.codelabs.ch/bob/ada.git
    branch: extend_als
    commit: 39ba5ca0aa6fabcb8f3dae271ea7395f4e72d177

  - name: codelabs
    scm: git
    url: https://git.codelabs.ch/bob/codelabs.git
    branch: main
    commit: cdc79ea7ba57cb9377f0b6e7473392886813fead

layersInclude:
  - override_layers
