bobMinimumVersion: "1.2.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/codelabs-ch/basement.git
    commit: 732314b52ac2cde0639706df9adf27d0f6793d7d
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/codelabs-ch/basement-gnu-linux.git
    commit: 0ba5619f2e7a40a85968af19b2e3e720bbd9f205
    branch: master

  - name: ada
    scm: git
    url: https://git.codelabs.ch/bob/ada.git
    branch: main
    commit: e457abe41e404b4e5310851d0fd015e1912a3765

  - name: codelabs
    scm: git
    url: https://git.codelabs.ch/bob/codelabs.git
    branch: main
    commit: d00ec60d664845c6d73d3a4ee31fab20554274d8

layersInclude:
  - override_layers
