environment:
  GRUB2_BOOTSTRAP: "1"
  GRUB2_TARGET: "i386"
  GRUB2_PLATFORM: "pc"
  GNULIB_URL: https://github.com/coreutils/gnulib.git
  GNU_MIRROR: https://mirror.init7.net/gnu/

scmOverrides:
  - match:
      url: ${GNU_MIRROR}/grub/grub-2.14.tar.gz
    del: [digestSHA256, stripComponents]
    set:
      scm: git
      url: https://github.com/codelabs-ch/grub2.git
      branch: bsbsc-2.14
      commit: 926721806af77cec29551030d2a962554732ba14

include:
  - user

archivePrepend:
  backend: http
  name: "bob archive"
  url: "https://bob-archive.codelabs.ch"
  sslVerify: true
  flags: [download]
